spring.application.name=teste
spring.datasource.url=jdbc:mysql://76.13.88.17:3306/u947092305_TCCTI27GRUPO4?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=u947092305_GRUPO4
spring.datasource.password=Fundatec@01
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate=DEBUG
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
logging.level.org.springframework.jdbc=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
api.security.token.secret=pipiroxoemurcho
