spring.application.name=teste
spring.datasource.url=jdbc:mysql://76.13.88.17:3306/u947092305_TCCTI27GRUPO4?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=u947092305_GRUPO4
spring.datasource.password=Fundatec@01
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate=DEBUG
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
logging.level.org.springframework.jdbc=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
api.security.token.secret=pipiroxoemurcho
cloudinary.cloud-name=t8awtqrh
cloudinary.api-key=128761653435369
cloudinary.api-secret=nsa_zSw2k2EV-T8AJmN1PIXL3nU
spring.datasource.hikari.maximum-pool-size=5


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.password=kfec bryh zqfc mxau
spring.mail.username=lucasmilhao26@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true 
spring.mail.properties.mail.smtp.starttls.required=true
